### ISSUE TITLE
pcbs-common Enhancement and Implementation

### ISSUE THREAD

**Issue by jadenreimer** [HeronMkII/pcbs#54]
List of things to change in pcbs-common design source files listed in the comments.

### **How to add pcbs-common files into your current Altium project:**
**Update your GitHub with the pcbs-common submodule**
Run these git commands from your ./pcbs folder:
`git submodule init .`
`git submodule update --remote pcbs-common`
**Get the files in your current project**
Project →  Add Existing to Project → navigate to your copy of pcbs-common → select relevant files for your design.
**Substitute your current subsheets with the pcbs-common versions**
Open properties of target subsheet (the green box) → find the label indicating from where it’s taking the current subsheet → select the ...  → navigate to the pcbs-common version in your project → select and OK that bad boy.
**Synchronize the lables to the subsheet with pcbs-common version**
Right click on the green box → sheet actions → synchronize sheet labels → select the pairs of corresponding sheet symbols → select the bottom arrow option (symbol of a beige box to a blue box [this pushes the version from pcbs-common onto the upper level]).
When you run out of things to link, select the remaining items in the middle column → add (bottom option) → add no ERCs (X symbols) to pins you are not currently using.

**Comment by jadenreimer** [comment]
- [ ] pex: VCCs are pointed down :(
can't remember other items

**Comment by brunofalmeida** [comment]
@vogeldylan 
- [ ] Does it make sense to repeat the component name in external ports? e.g. for the ADC schematic sheet, should the port be called `GPIO` instead of `ADC_GPIO` since from context it's known to belong to the ADC? When that sheet is incorporated in a higher level sheet, it should definitely have ADC in the name though.
- [ ] Typo in adc-circit-ADS7952 ("circuit")
- [ ] In adc-circit-ADS7952, recommended input impedance is < XX?
